name: misspell
on: [pull_request]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1.1.5
        with:
          reporter: github-pr-check
          github_token: ${{ secrets.github_token }}
          locale: "US"
